name 'chef_gem'
maintainer 'Chris Roberts'
maintainer_email 'chrisroberts.code@gmail.com'
license 'Apache-2.0'
description 'Provides proper chef_gem resource support for Chef versions < 0.10.12'
version '0.1.0'
