#!/usr/bin/env bash

set -o errexit

[[ $# -ge 1 ]]

COOKBOOK_PATH="$1"

: ${FC_ARGS:=}
: ${FC_TAGS:=$COOKBOOK_PATH/.foodcritic-tags}

if [[ -f ${FC_TAGS} ]] ; then
  for tag in $(cat ${FC_TAGS}) ; do
    FC_ARGS="$FC_ARGS --tags $tag"
  done
fi

HAD_FAIL=

for cookbook in $(find $COOKBOOK_PATH -maxdepth 1 -type d | grep -v 'cookbooks$') ; do
  cookbook_name=$(basename $cookbook)
  foodcritic_command="foodcritic --epic-fail any $FC_ARGS $cookbook"
  echo : $foodcritic_command
  if $foodcritic_command ; then
    echo "---> $cookbook_name ✔︎"
  else
    echo "---> $cookbook_name ✘"
    HAD_FAIL=1
  fi
done

if [[ $HAD_FAIL ]] ; then
  exit 1
else
  exit 0
fi
