#!/usr/bin/env bash

set -o errexit

: ${COOKBOOK_PATH:=cookbooks}

unset GEM_PATH

cd "$(dirname ${BASH_SOURCE[0]})"

# if [[ -f $COOKBOOK_PATH/.rubocop.yml ]] ; then
  # echo "Testing with RuboCop $(rubocop --verbose-version)"
  # (cd $COOKBOOK_PATH && rubocop)
# fi

echo "Testing with $(cookstyle --version)"
./run-cookstyle $COOKBOOK_PATH
