maintainer       "Travis CI Development Team"
license          "Apache v2.0"
name             "libyaml"
version          "1.0.0"
description      "libyaml"
long_description "Installs/Configures libyaml"
