name 'travis_rvm'
maintainer 'Travis CI GmbH'
maintainer_email 'contact+travis-cookbooks-travis-rvm@travis-ci.org'
license 'MIT'
description 'Travis specific additions for RVM fun'
version '0.1.0'

depends 'rvm'
depends 'java'
depends 'ant'
