maintainer        "Loïc Frering"
maintainer_email  "loic.frering@gmail.com"
license           "Apache 2.0"
description       "Installs phpfarm and phpenv for multiple PHP versions management."
version           "1.0.0"

depends "build-essential"
depends "apt"
depends "phpfarm"
depends "phpenv"
