maintainer       "Travis CI Development Team"
license          "Apache v2.0"
name             "openssh"
version          "1.0.0"
description      "openssh"
long_description "Installs/Configures openssh"
