AllCops:
  Exclude:
    - 'Guardfile'
    - 'tmp/**/*'
    - 'cookbooks/**/*'

Layout/ParameterAlignment:
  Enabled: false

Style/Encoding:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

# HashSyntax:
#  EnforcedStyle: hash_rockets

Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/GuardClause:
  Enabled: false

# TODO: remove override for ModuleLength once RunitCookbook::Helpers has been refactored
Metrics/ModuleLength:
  Max: 150

Chef/Modernize/SetOrReturnInResources:
  Enabled: false

Chef/Deprecations/Cheffile:
  Enabled: false