name              "php"
maintainer        "Loïc Frering"
maintainer_email  "loic.frering@gmail.com"
license           "Apache 2.0"
description       "Installs php-build and phpenv for multiple PHP versions management."
version           "1.0.0"

depends "apt"
depends "build-essential"
depends "composer"
depends "phpbuild"
depends "phpenv"
