name 'travis_build_environment'
maintainer 'Travis CI Development Team'
license 'Apache v2.0'
version '1.1.0'
description 'Travis build environment'
long_description 'Travis build environment'

depends 'iptables'
depends 'openssh'
depends 'sysctl'
depends 'travis_timezone'
depends 'unarchivers'
