maintainer       'Travis CI Development Team'
license          'Apache v2.0'
name             'travis_build_environment'
version          '1.1.0'
description      'Travis build environment'
long_description 'Travis build environment'

depends 'travis_timezone'
depends 'sysctl'
depends 'openssh'
depends 'unarchivers'
depends 'iptables'
