default[:leiningen][:version] = "1.6.1"
default[:leiningen][:install_script] = "https://github.com/technomancy/leiningen/raw/#{leiningen[:version]}/bin/lein"
default[:leiningen][:jar_url] = "http://github.com/downloads/technomancy/leiningen/leiningen-#{leiningen[:version]}-standalone.jar"
default[:leiningen][:jar_checksum] = "a55e14132cdbef24ac0c08ad340746ad"
default[:leiningen][:jar_dir] = "/usr/share/java"
