maintainer       "Travis CI Development Team"
license          "Apache v2.0"
name             "libncurses"
version          "1.0.0"
description      "libncurses"
long_description "Installs/Configures libncurses"
