maintainer       "Travis CI Development Team"
license          "Apache v2.0"
name             "networking_basic"
version          "1.0.0"
description      "networking_basic"
long_description "Installs/Configures networking_basic"
