name 'packagecloud'
maintainer 'Joe Damato'
maintainer_email 'joe@packagecloud.io'
license 'Apache-2.0'
description 'Installs/Configures packagecloud.io repositories.'
version '0.2.4'
source_url 'https://github.com/computology/packagecloud-cookbook'
issues_url 'https://github.com/computology/packagecloud-cookbook/issues'
